### ISSUE TITLE
TO-DO TILL PUBLIC RELEASE

### ISSUE THREAD

**Issue by volzeyy** [Volzeyy/endsbox#1]
- [x] **Re-design the app in Figma**
- [x] **RE-WRITE**
- [x] Make a tool that lets the user upload images and gifs to the user's own box
- [x] Make the elements moveable
- [x] Make the elements deletable
- [x] Make the elements resizeable
- [x] Add a tool that allows the user to customize the background image/color of their box
- [x] Add a Sandbox
- [x] Add Routing
- [x] Connect everything to Firebase
- [x] Integrate Google Authentication
- [x] Integrate a Username system
- [x] Add Home Page/ Product Page
- [x] Add the option to purchase a monthly subscription
- [x] **Add support for Mobile**
- [x] **VALIDATE EVERYTHING!!!**
